server {
    listen 80;

    # Allow requests only from CloudFront
    # using custom secret header validation
    if ($http_p_origin_access != "Ephemeral") {
        return 403;
    }

    location / {

        # Forward requests to Flask application container
        proxy_pass http://app:8000;

        # Forward original client request details
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
