server {
    listen 80;

    # Allow only CloudFront traffic
    if ($http_p_origin_access != "Ephemeral") {
        return 403;
    }

    location / {
        proxy_pass http://app:8000;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
