name: EC2 Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: 3.83.97.211   
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd ~/dockerized-ephemeral-messaging-system-aws
            git fetch origin
            git reset --hard origin/main
            sudo docker compose down
            sudo docker compose up --build -d
